spring.application.name=app-livros
server.port=8080

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always
management.info.env.enabled=true

info.app.name=App Livros
info.app.version=1.0.0
info.app.description=API REST de catalogo de livros
